version: '3.5'
services:
    # App service
    book_service:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        image: book_service
        privileged: true
        container_name: book_service
        restart: unless-stopped
        tty: true
        working_dir: /var/www/app/
        volumes:
            - ./:/var/www/app/
            - ./docker/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
        networks:
            - book_network

    # Web server
    book_server:
        image: nginx:alpine
        container_name: book_server
        restart: on-failure
        tty: true
        ports:
            - "${APP_PORT:-8283}:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
            - ./:/var/www/app:cached
        depends_on:
            - book_service
        networks:
            - book_network

#Docker Networks
networks:
    book_network:
        driver: bridge
